/*
===============================================================================
 Query:      Summary_New__Players
 Version:    vDraft.4
 Purpose:    
 Author:     Mike Avery
 Created:    2026-01-08
 Source:     Indiv_Results_Staging
 Layer:      Summary_New
-------------------------------------------------------------------------------
 Design Principles:
 - Source(s) Indiv_Results_Staging, Summary_New__Season
 - No file system access
 - No business rule inference
 - Schema must be stable even when no data exists
===============================================================================
*/

let
    // ============================================================
    // SECTION 0 — SEASON CONTEXT (Static_Season_Config)
    // ============================================================

    AllSeasonSettings =
        qry_Static_Season_Config,

    ActiveSeasonRows =
        Table.SelectRows(
            AllSeasonSettings,
            each [SettingKey] = "SeasonStatus"
                and [SettingValue] = "Active"
        ),

    ActiveSeasonCount =
        Table.RowCount(ActiveSeasonRows),

    CurrentSeasonKey =
        if ActiveSeasonCount = 1 then
            ActiveSeasonRows{0}[SeasonKey]
        else if ActiveSeasonCount = 0 then
            error "No Active season found in Static_Season_Config
                (SeasonStatus=Active)."
        else
            error "Multiple Active seasons found in Static_Season_Config.
                Expected exactly 1.",

    SeasonRows =
        Table.SelectRows(
            AllSeasonSettings,
            each [SeasonKey] = CurrentSeasonKey
        ),

    GetSeasonScalar =
        (key as text) as any =>
            let
                rows =
                    Table.SelectRows(
                        SeasonRows,
                        each [SettingKey] = key
                    ),
                n = Table.RowCount(rows)
            in
                if n = 1 then
                    rows{0}[SettingValue]
                else if n = 0 then
                    error "Missing required season setting '" & key & "'."
                else
                    error "Non-scalar season setting '" & key & "'.",

    SeasonYear_Value =
        GetSeasonScalar("SeasonYear"),

    //-----------------------------------------------------------------------

    Source = Indiv_Results_Staging,

        SelectCols =
            Table.SelectColumns(
                Source,
                {
                    "SeasonYear",
                    "Player",
                    "PlayerKey",
                    "Team",
                    "MatchWeek",
                    "MatchDate"
                }
            ),

        SortLatest =
            Table.Sort(
                SelectCols,
                {
                    {"Player", Order.Ascending},
                    {"MatchWeek", Order.Descending},
                    {"MatchDate", Order.Descending}
                }
            ),

        OneRowPerPlayer =
            Table.Distinct(
                SortLatest,
                {"Player"}
            ),

        AddFields =
            Table.TransformColumns(
                Table.AddColumn(OneRowPerPlayer, "ActiveStatus", each "Active",
                    type text),
                {}
            ),

        AddIsCaptain =
            Table.AddColumn(AddFields, "IsCaptain", each null, type logical),

        AddTee =
            Table.AddColumn(AddIsCaptain, "Tee", each null, type text),

        AddRosterDates =
            Table.AddColumn(AddTee, "RosterStartDate", each null, type date),

        AddRosterEnd =
            Table.AddColumn(AddRosterDates, "RosterEndDate", each null,
                type date),

        AddContact =
            Table.AddColumn(AddRosterEnd, "PlayerPhone", each null, type text),

        AddEmail =
            Table.AddColumn(AddContact, "PlayerEmail", each null, type text),

        Final =
            Table.SelectColumns(
                AddEmail,
                {
                    "SeasonYear",
                    "Player",
                    "PlayerKey",
                    "Team",
                    "ActiveStatus",
                    "IsCaptain",
                    "Tee",
                    "RosterStartDate",
                    "RosterEndDate",
                    "PlayerPhone",
                    "PlayerEmail"
                }
            )

in
    Final

/* Version History

    vDraft.4 - 2026-01-08
    - Added code generated by GPT-5.2 to correct errors in vDraft.3, including...
      > Binding the query to a validated, active season.
      > Added retrieval of SeasonYear from season context.

    vDraft.3 - 2025-12-31 
    - Removed ExclScore code block and added note to clarify handling of score
      exclusions.
    - Removed code to derive and add key fields (SeasonYear, PlayerKey, TeamKey)
      as these are now included in the source table.

    vDraft.2 - 2025-12-

    vDraft.1 - 2025-12-

    v1.0 - 2025-12- - Initial version

*/