/*
===============================================================================
 Query:      Summary_New__Handicaps
 Version:    vDraft.4
 Purpose:    
 Author:     Mike Avery
 Created:    2026-01-07
 Source:     Handicap_Engine (future), Player_Master (future),
             Static_Season_Config, Summary_New__Player_Stats
 Layer:      Summary_New
-------------------------------------------------------------------------------
 Design Principles:
 - Source(s) (TBD)
 - No file system access
 - No business rule inference
 - Schema must be stable even when no data exists
-------------------------------------------------------------------------------
 Notes:
 - Section D in schema
 - No business logic
 - No inference
 - Populated later by engines
===============================================================================
*/

let

    // ============================================================
    // SECTION 0 — SEASON CONTEXT (Static_Season_Config)
    // ============================================================

    AllSeasonSettings =
        qry_Static_Season_Config,

    ActiveSeasonRows =
        Table.SelectRows(
            AllSeasonSettings,
            each [SettingKey] = "SeasonStatus"
                and [SettingValue] = "Active"
        ),

    ActiveSeasonCount =
        Table.RowCount(ActiveSeasonRows),

    CurrentSeasonKey =
        if ActiveSeasonCount = 1 then
            ActiveSeasonRows{0}[SeasonKey]
        else if ActiveSeasonCount = 0 then
            error "No Active season found in Static_Season_Config
                (SeasonStatus=Active)."
        else
            error "Multiple Active seasons found in Static_Season_Config.
                Expected exactly 1.",

        SeasonRows =
        Table.SelectRows(
            AllSeasonSettings,
            each [SeasonKey] = CurrentSeasonKey
        ),

    GetSeasonScalar =
        (key as text) as any =>
            let
                rows =
                    Table.SelectRows(
                        SeasonRows,
                        each [SettingKey] = key
                    ),
                n = Table.RowCount(rows)
            in
                if n = 1 then
                    rows{0}[SettingValue]
                else if n = 0 then
                    error "Missing required season setting '" & key & "'."
                else
                    error "Non-scalar season setting '" & key & "'.",

    SeasonYear_Value =
        GetSeasonScalar("SeasonYear"),

    //-----------------------------------------------------------------------
    // 1) Placeholder source (no Player_Master yet)
    //-----------------------------------------------------------------------
    Source =
        #table(
            type table[
                Player = text,
                PlayerKey = text,
                IsActive = logical
            ],
            {}
        ),

    //-----------------------------------------------------------------------
    // 4) Add required schema columns (engine-owned later)
    //-----------------------------------------------------------------------
    
    AddSeasonYear =
        Table.AddColumn(
            Source,
            "SeasonYear",
            each SeasonYear_Value,
            type number
        ),
    
    AddEstablishedHcp =
        Table.AddColumn(
            AddSeasonYear,
            "EstablishedHcp",
            each null,
            type logical
        ),

    AddHandicap =
        Table.AddColumn(
            AddEstablishedHcp,
            "Handicap",
            each null,
            type number
        ),

    AddHandicapCalcBasis =
        Table.AddColumn(
            AddHandicap,
            "HandicapCalcBasis",
            each null,
            type text
        ),

    AddHandicapRounds =
        Table.AddColumn(
            AddHandicapCalcBasis,
            "HandicapRounds",
            each null,
            type number
        ),

    AddSeasonRoundsPlayed =
        Table.AddColumn(
            AddHandicapRounds,
            "SeasonRoundsPlayed",
            each null,
            type number
        ),

    //-----------------------------------------------------------------------
    // 5) Final schema projection
    //-----------------------------------------------------------------------
    Final =
        Table.SelectColumns(
            AddSeasonRoundsPlayed,
            {
                "SeasonYear",
                "Player",
                "PlayerKey",
                "EstablishedHcp",
                "Handicap",
                "HandicapCalcBasis",
                "HandicapRounds",
                "SeasonRoundsPlayed"
            }
        )
in
    Final
/* 
Version History

    vDraft.4 2026-01-07
    - Code generated by GPT-5.2 to correct errors in vDraft.3, including...
      > Binding the query to a validated, active season.
      > Added retrieval of SeasonYear from season context.
    
    vDraft.3 2025-12-27
    - 

    vDraft.2 2025-12-
    - 

    vDraft.1 2025-12
    - 

    v1.0  2025-12-
    - Original version

*/